### ISSUE TITLE
Implement Encode and Decode for HashSet

### ISSUE THREAD

**Issue by devashishdxt** [paritytech/parity-scale-codec#127]
Currently, `Encode` and `Decode` traits are not implemented for `HashMap`, `HashSet` and also `BTreeSet`.

**Comment by bkchr** [comment]
`HashMap` and `HashSet` do not work on `no_std`. `BTreeSet` could probably be implemented.

**Comment by bkchr** [comment]
Okay, BTreeSet is already implemented on master. So, I will close this.

**Comment by tdelabro** [comment]
In no_std we tend to use [hashbrown](https://github.com/rust-lang/hashbrown) in order to still be able to use HashMap and HashSet.

Would you be open to a `hashbrown` feature being added (optional dep) and implementing `Encode` and `Decode` for both std::collection::HashMap/HashSet and hashbrown::HashMap/HashSet?

**Comment by koute** [comment]
@tdelabro In general supporting `HashMap`s/`HashSet`s is a potential trap that can introduce non-determinism, so I probably wouldn't want to support it *by default*. If someone uses a `HashMap`/`HashSet` in their runtime they *really* need to know what they're doing.

That said, assuming this would be under a feature flag, the major issue here would be that the serialization order is going to depend on the exact hash algorithm used and on the exact version of `hashbrown`, which means that using a hash algorithm that's not guaranteed to be stable or just bumping the dependencies could change the serialized payload (either using a new version of `hashbrown` because it doesn't guarantee any iteration order, or bumping the crate with the hashing algorithm if it's not guaranteed to not change across versions). For blockchain-related applications this would be a very nasty trap that could bite people down the line! And there's also the issue of potentially introducing a DoS attack vector if the hash function isn't designed to withstand such attacks.

All in all, I'm not entirely convinced we should support `HashMap`s/`HashSet`s as, again, you really need to know what you're doing if you're using them and need to be aware of all of the subtle traps that can make your life miserable later.

**Comment by tdelabro** [comment]
Hi @koute 
Thanks a lot for those info. I have to confess I'm a bit afraid after this answer.
May I ask you more information about those risks?

Currently we are running a VM in our runtime that uses hash maps internally for its execution.
What are the dangers of having this lib using hasmaps executed in the runtime? What should we be careful of?

When we need to store, in substrate storage, some data type from the VM that contains a hash map, we convert the  hashmap to a vector of key/value tupple that we encode. Same in reverse for decoding
Do you think it could cause bugs?

**Comment by koute** [comment]
> What are the dangers of having this lib using hasmaps executed in the runtime? What should we be careful of?

Basically, for `hashbrown` in particular its iteration order is *not* guaranteed, nor the amount of memory it consumes. It can differ between versions, and it could even differ between different recompilations (with the default hash function that it uses). So if there's *anything* which depends on this order in a way that e.g. will affect the storage root then that could, eventually, brick your chain if the iteration order changes in the future and the code still expects the old iteration order.

Another problem is that if the hash function is not resistant to a DoS attack (called [a HashDoS or hash flooding](https://en.wikipedia.org/wiki/Collision_attack#Hash_flooding)) and the keys of the hash map can be controlled externally then a malicious attacker could engineer the inputs so that hash lookups stop being O(1) and start being O(n), which can be disastrous in certain situations. 

Now, I don't know your code nor how exactly you're using the hashmaps, so I'm not saying this will happen to you; just that it is a possibility depending on how the hashmaps are used. It might not be a problem at all. If you're careful and you're aware of all of the pitfalls then it's possible to use hashmaps safely inside of a runtime.

A quick empirical test you could do which would show you if you have a problem (but if it doesn't fail it **doesn't** necessarily guarantee that you are okay) would be to take your existing use of a `HashMap` and replace the hashing algorithm it uses (which should change its iteration order and in corner cases possibly the amount of memory it consumes) and run that on an existing node on a testnet along with other unmodified nodes and see if it crashes.

In general when in doubt it's just better to use a `BTreeMap`/`BTreeSet` inside of a runtime, unless you have extreme performance requirements. Have you tried to replace your use of a `HashMap` with a `BTreeMap` and see how that affects you? Maybe you don't actually need a `HashMap`?
